require('dotenv').config();
module.exports={
    HOST:"127.0.0.1",
    USER:process.env.DB_USERNAME,
    PASSWORD:process.env.PASSWORD,
    DB:"chetan_machine_test",
    dialect:"mysql",
    pool:{
        max:5,
        min:0,
        acquire:30000,
        idle:10000
    }
};